{{- $serviceMesh := include "eric-oss-pm-stats-exporter.service-mesh-enabled" . | trim -}}
{{- $tls := include "eric-oss-pm-stats-exporter.global-security-tls-enabled" . | trim -}}

#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
data:
  application.properties: |
    management.endpoint.metrics.enabled=true
    management.endpoints.web.exposure.include=*
    management.endpoint.prometheus.enabled=true
    management.metrics.export.prometheus.enabled=true
    management.metrics.web.server.auto-time-requests=true
kind: ConfigMap
metadata:
  name: {{ include "eric-oss-pm-stats-exporter.configmap.name" . }}
  labels:
    {{- include "eric-oss-pm-stats-exporter.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-oss-pm-stats-exporter.annotations" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eric-oss-pm-stats-exporter.fullname" . }}
  labels:
    {{- include "eric-oss-pm-stats-exporter.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-oss-pm-stats-exporter.annotations" . | nindent 4 }}
spec:
{{- if not .Values.autoScaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eric-oss-pm-stats-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  strategy:
    type: {{ .Values.updateStrategy.type | quote }}
    {{- if and (eq .Values.updateStrategy.type "RollingUpdate") .Values.updateStrategy.rollingUpdate }}
    rollingUpdate:
      maxUnavailable: {{ .Values.updateStrategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.updateStrategy.rollingUpdate.maxSurge }}
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "eric-oss-pm-stats-exporter.containerLabels" . | nindent 8 }}
      annotations:
        {{- include "eric-oss-pm-stats-exporter.containerAnnotations" . | nindent 8 }}
    spec:
      {{- if include "eric-oss-pm-stats-exporter.pullSecret" . }}
      imagePullSecrets:
        - name: {{ include "eric-oss-pm-stats-exporter.pullSecret" . }}
      {{- end }}
      serviceAccountName: {{ include "eric-oss-pm-stats-exporter.fullname" . }}
      securityContext:
        fsGroup: {{ include "eric-oss-pm-stats-exporter.fsGroup.coordinated" . }}
        {{ include "eric-oss-pm-stats-exporter.supplementalGroups" . }}
      volumes:
        - name: "tmp-volume"
          emptyDir: {}
        - name: "config-volume"
          configMap:
            name: {{ include "eric-oss-pm-stats-exporter.configmap.name" . }}
        - name: "log-control-configmap-volume"
          configMap:
            name: {{ include "eric-oss-pm-stats-exporter.log-control-configmap.name" . }}
      containers:
        - name: "eric-oss-pm-stats-exporter"
          image: {{ include "eric-oss-pm-stats-exporter.mainImagePath" . }}
          imagePullPolicy: {{ include "eric-oss-pm-stats-exporter.registryImagePullPolicy" . }}
          securityContext:
            {{- include "eric-oss-pm-stats-exporter.seccomp-profile" . | indent 12 }}
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 40514
            capabilities:
              drop:
                - all
          volumeMounts:
            - mountPath: "/tmp"
              name: "tmp-volume"
            - name: "config-volume"
              mountPath: "/config"
            - name: "log-control-configmap-volume"
              mountPath: "/logcontrol"
          ports:
            - name: "http"
              containerPort: 8080
              protocol: "TCP"
          livenessProbe:
          {{- if (index .Values "probes" "eric-oss-pm-stats-exporter" "livenessProbe" "initialDelaySeconds") }}
            {{ print "initialDelaySeconds: " (index .Values "probes" "eric-oss-pm-stats-exporter" "livenessProbe" "initialDelaySeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-pm-stats-exporter" "livenessProbe" "failureThreshold") }}
            {{ print "failureThreshold: " (index .Values "probes" "eric-oss-pm-stats-exporter" "livenessProbe" "failureThreshold") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-pm-stats-exporter" "livenessProbe" "periodSeconds") }}
            {{ print "periodSeconds: " (index .Values "probes" "eric-oss-pm-stats-exporter" "livenessProbe" "periodSeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-pm-stats-exporter" "livenessProbe" "timeoutSeconds") }}
            {{ print "timeoutSeconds: " (index .Values "probes" "eric-oss-pm-stats-exporter" "livenessProbe" "timeoutSeconds") }}
          {{- end }}
            httpGet:
              path: "/actuator/health"
              port: "http"
          readinessProbe:
          {{- if (index .Values "probes" "eric-oss-pm-stats-exporter" "readinessProbe" "initialDelaySeconds") }}
            {{ print "initialDelaySeconds: " (index .Values "probes" "eric-oss-pm-stats-exporter" "readinessProbe" "initialDelaySeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-pm-stats-exporter" "readinessProbe" "failureThreshold") }}
            {{ print "failureThreshold: " (index .Values "probes" "eric-oss-pm-stats-exporter" "readinessProbe" "failureThreshold") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-pm-stats-exporter" "readinessProbe" "periodSeconds") }}
            {{ print "periodSeconds: " (index .Values "probes" "eric-oss-pm-stats-exporter" "readinessProbe" "periodSeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-pm-stats-exporter" "readinessProbe" "timeoutSeconds") }}
            {{ print "timeoutSeconds: " (index .Values "probes" "eric-oss-pm-stats-exporter" "readinessProbe" "timeoutSeconds") }}
          {{- end }}
            httpGet:
              path: "/actuator/health"
              port: "http"
          env:
            - name: SERVICE_ID
              value: {{ include "eric-oss-pm-stats-exporter.name" . }}
            - name: JAVA_OPTS
              value: {{ include "eric-oss-pm-stats-exporter.jvmHeapSettings" . }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BROKER_ADDRESS
              value: {{ .Values.kafka.brokerAddress | quote }}
            - name: BROKER_PORT
              value: {{ include "eric-oss-pm-stats-exporter.kafka-bootstrap-port" . }}
            {{- with index .Values "kafka" }}
            - name: KAFKA_ENABLED
              value: {{ .enabled | quote }}
            {{- if eq (index .enabled) true }}
            - name: EXECUTION_REPORT_TOPIC_NAME
              value: {{ .executionReport.topicName | quote }}
            - name: SCHEMA_REGISTRY_URL
              value: {{ .schemaRegistryUrl | quote }}
            - name: GROUP_ID
              value: {{ .consumer.groupId | quote}}
            - name: AVRO_PRODUCER_LINGER_MS
              value: {{ .producer.avro.linger | quote }}
            - name: AVRO_PRODUCER_BATCH_SIZE
              value: {{ .producer.avro.batchSize | quote }}
            - name: AVRO_PRODUCER_COMPRESSION_TYPE
              value: {{ .producer.avro.compressionType | quote }}
            - name: BACKUP_TOPIC_NAME
              value: {{ .backup.topicName | quote }}
            - name: BACKUP_TOPIC_PARTITIONS
              value: {{ .backup.partitions | quote }}
            - name: BACKUP_TOPIC_REPLICATION_FACTOR
              value: {{ .backup.replicationFactor | quote }}
            - name: COMPLETED_TIMESTAMP_TOPIC_NAME
              value: {{ .completedTimestamp.topicName | quote }}
            - name: COMPLETED_TIMESTAMP_TOPIC_PARTITIONS
              value: {{ .completedTimestamp.partitions | quote }}
            - name: COMPLETED_TIMESTAMP_TOPIC_REPLICATION_FACTOR
              value: {{ .completedTimestamp.replicationFactor | quote }}
            - name: SCHEDULED_TOPIC_NAME
              value: {{ .scheduled.topicName | quote }}
            - name: SCHEDULED_TOPIC_PARTITIONS
              value: {{ .scheduled.partitions | quote }}
            - name: SCHEDULED_TOPIC_REPLICATION_FACTOR
              value: {{ .scheduled.replicationFactor | quote }}
            - name: ON_DEMAND_TOPIC_NAME
              value: {{ .onDemand.topicName | quote }}
            - name: ON_DEMAND_TOPIC_PARTITIONS
              value: {{ .onDemand.partitions | quote }}
            - name: ON_DEMAND_TOPIC_REPLICATION_FACTOR
              value: {{ .onDemand.replicationFactor | quote }}
            {{- end }}
            {{- end }}
            - name: TZ
              value: {{ template "eric-oss-pm-stats-exporter.timezone" . }}
            - name: POSTGRES_ENABLED
              value: {{ index .Values "eric-pm-kpi-data" "enabled" | quote }}
            {{- if eq (index .Values "eric-pm-kpi-data" "enabled") true }}
            - name: POSTGRES_HOSTNAME
              value: {{ include "eric-oss-pm-stats-exporter.database-host" . }}
            - name: POSTGRES_PORT
              value: {{ index .Values "eric-pm-kpi-data" "service" "port" | quote }}
            - name: POSTGRES_DATABASE
              value: {{ index .Values "eric-pm-kpi-data" "postgresDatabase" | quote }}
            {{- if and (eq $serviceMesh "true") (eq $tls "true") }}
            - name: POSTGRES_USER
              value: {{ index .Values "eric-pm-kpi-data" "credentials" "roUserName" | quote }}
            - name: POSTGRES_PASSWORD
              value: ""
            {{- else }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ index .Values "eric-pm-kpi-data" "credentials" "kubernetesSecretName" | quote }}
                  key: {{ index .Values "eric-pm-kpi-data" "credentials" "keyForUserId" | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ index .Values "eric-pm-kpi-data" "credentials" "kubernetesSecretName" | quote }}
                  key: {{ index .Values "eric-pm-kpi-data" "credentials" "keyForUserPw" | quote }}
            {{- end }}
            {{- end }}
            {{- with index .Values "retry" }}
            - name: KAFKA_RETRY_BACKOFF_PERIOD
              value: {{ .kafka.backoffPeriod | quote }}
            - name: KAFKA_MAX_RETRY_ATTEMPTS
              value: {{ .kafka.maxAttempts | quote }}
            - name: TOPICS_RETRY_BACKOFF_PERIOD
              value: {{ .topics.backoffPeriod | quote }}
            - name: TOPICS_MAX_RETRY_ATTEMPTS
              value: {{ .topics.maxAttempts | quote }}
            - name: POSTGRES_RETRY_BACKOFF_PERIOD
              value: {{ .postgres.backoffPeriod | quote }}
            - name: POSTGRES_MAX_RETRY_ATTEMPTS
              value: {{ .postgres.maxAttempts | quote }}
            - name: SR_RETRY_BACKOFF_PERIOD
              value: {{ .sr.backoffPeriod | quote }}
            - name: SR_MAX_RETRY_ATTEMPTS
              value: {{ .sr.maxAttempts | quote }}
            {{- end }}
            - name: POSTGRES_CONFIG
              value: {{ template "eric-oss-pm-stats-exporter.jdbc-config" . }}
            {{- with index .Values "dmm" }}
            - name: DC_ENABLED
              value: {{ .enabled | quote }}
            {{- if eq (index .enabled) true }}
            - name: DC_ADDRESS
              value: "http://{{ .dataCatalog.nameOverride }}:{{ .dataCatalog.service.port }}"
            {{- end }}
            {{- end }}
            {{- with index .Values "meterCollectors" }}
            - name: METERCOLLECTORS_ENABLED
              value: {{ .enabled | quote }}
            {{- if eq (index .enabled) true }}
            - name: METERCOLLECTORS_RETENTION_SECONDS
              value: {{ .retentionSeconds | quote }}
            {{- end }}
            {{- end }}
        {{- if .Values.global }}
          {{- if .Values.global.security }}
            {{- if .Values.global.security.tls }}
              {{- if .Values.global.security.tls.enabled }}
            - name: CONNECT_MODE
              value: "tls"
              {{- if (eq .Values.service.endpoints.chassisapi.tls.enforced "required") }}
            - name: TLS_MODE
              value: "only_tls"
              {{- if (eq .Values.service.endpoints.chassisapi.tls.verifyClientCertificate "required") }}
            - name: TLS_CA
              value: "ca_path"
              {{- end }}
              {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
            - name: KUBERNETES_LEADER_CONFIG_MAP_NAME
              value: {{ .Values.leaderConfigMapName | quote }}
            - name: LOG_CTRL_FILE
              value: {{ .Values.log.logControlFile }}
        {{- include "eric-oss-pm-stats-exporter.loggingEnv" . | nindent 12 }}
        {{- include "eric-oss-pm-stats-exporter.dstEnv" . | nindent 12 }}
          resources:
            requests:
            {{- if (index .Values "resources" "eric-oss-pm-stats-exporter" "requests" "cpu") }}
              cpu: {{ (index .Values "resources" "eric-oss-pm-stats-exporter" "requests" "cpu" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-pm-stats-exporter" "requests" "memory") }}
              memory: {{ (index .Values "resources" "eric-oss-pm-stats-exporter" "requests" "memory" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-pm-stats-exporter" "requests" "ephemeral-storage") }}
            {{ println "  ephemeral-storage:" (index .Values "resources" "eric-oss-pm-stats-exporter" "requests" "ephemeral-storage" | quote) }}
            {{- end }}
            limits:
            {{- if (index .Values "resources" "eric-oss-pm-stats-exporter" "limits" "cpu") }}
              cpu: {{ (index .Values "resources" "eric-oss-pm-stats-exporter" "limits" "cpu" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-pm-stats-exporter" "limits" "memory") }}
              memory: {{ (index .Values "resources" "eric-oss-pm-stats-exporter" "limits" "memory" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-pm-stats-exporter" "limits" "ephemeral-storage") }}
            {{ println "  ephemeral-storage:" (index .Values "resources" "eric-oss-pm-stats-exporter" "limits" "ephemeral-storage" | quote) }}
            {{- end }}
      nodeSelector: {{- include "eric-oss-pm-stats-exporter.nodeSelector" . | nindent 6 -}}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds:
        {{- include "eric-oss-pm-stats-exporter.terminationGracePeriodSeconds" . | nindent 8 -}}
      {{- end }}

      {{ if .Values.tolerations }}
      tolerations: {{ include "eric-oss-pm-stats-exporter.merge-tolerations" . | nindent 8 }}
      {{ else if .Values.global }}
        {{ if .Values.global.tolerations }}
          tolerations: {{ include "eric-oss-pm-stats-exporter.merge-tolerations" . | nindent 8 }}
        {{ end }}
      {{ end }}

      {{- with .Values.topologySpreadConstraints.deployment }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if eq .Values.affinity.podAntiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: "In"
                    values:
                      - {{ include "eric-oss-pm-stats-exporter.name.noQuote" . }}
              topologyKey: {{ .Values.affinity.topologyKey }}
      {{- else if eq .Values.affinity.podAntiAffinity  "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: "In"
                      values:
                        - {{ include "eric-oss-pm-stats-exporter.name.noQuote" . }}
                topologyKey: {{ .Values.affinity.topologyKey }}
      {{- end }}
      {{- if (index .Values "podPriority" "eric-oss-pm-stats-exporter" "priorityClassName") }}
      priorityClassName: {{ (index .Values "podPriority" "eric-oss-pm-stats-exporter" "priorityClassName") | quote }}
      {{- end }}
