#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eric-oss-pm-stats-exporter.rolebinding-allowed-use-privileged.name" . }}
  labels:
    {{- include "eric-oss-pm-stats-exporter.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-oss-pm-stats-exporter.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "eric-oss-pm-stats-exporter.rolebinding-allowed-use-privileged.roleRef.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "eric-oss-pm-stats-exporter.name" . }}