#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

imageCredentials:
  pullSecret: armdocker

replicaCount: 1

probes:
  eric-oss-pm-stats-exporter:
    livenessProbe:
      initialDelaySeconds: 120
    readinessProbe:
      initialDelaySeconds: 120

kafka:
  enabled: true
  brokerAddress: "eric-data-message-bus-kf"
  schemaRegistryUrl: "http://schemaregistry:8081/"

eric-pm-kpi-data:
  enabled: true

dmm:
  enabled: true

global:
  registry:
    imagePullPolicy: "Always"

log:
  streamingMethod: indirect
  logLevel: DEBUG