{{- $serviceMesh := include "eric-oss-pm-stats-exporter.service-mesh-enabled" . | trim -}}
{{- $tls := include "eric-oss-pm-stats-exporter.global-security-tls-enabled" . | trim -}}
{{- if and (eq $serviceMesh "true") (eq $tls "true") -}}

#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ include "eric-oss-pm-stats-exporter.name.noQuote" . }}-eric-log-transformer-int-cert
  labels:
  {{- include "eric-oss-pm-stats-exporter.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-pm-stats-exporter.annotations" . | nindent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ include "eric-oss-pm-stats-exporter.name.noQuote" . }}-eric-log-transformer-secret
    certificateName: "cert.pem"
    privateKeyName: "key.pem"
  certificate:
    subject:
      cn: {{ include "eric-oss-pm-stats-exporter.name" . }}
    issuer:
      reference: eric-log-transformer-input-ca-cert
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: true
{{- end }}